# your domain
domain: example.com
port:                 # default 12580
tls_enable:
cert_file: ""
key_file: ""

# source list file
source-files:
  # use local file
  - ./config/source.yaml
  # use web file
  # - https://example.com/config/source.yaml

# ======= 可选项，留空使用default值  =======

# postgresql database info
database_url: ""

# interval between each crawling
crawl-interval:       # v0.5.x default 60 (minutes)
crontime:             # v0.4.x default 60 (minutes). Deprecated in the newest version

# speed test
speedtest: false      # default false. Warning: this will consume large network resources.
speedtest-interval:   # default 720 (min)
# AE,BE,CA,TW,DE,HK,IT,PL,US
speed-country-white-list: "Relay,AE,BE,CA,TW,DE,HK,IT,JP,PL,US"
connection:           # default 5. The number of speed test connections simultaneously
timeout:              # default 10 (seconds).
## active proxy speed test
active-interval:      # default 60 (min)
active-frequency:     # default 100 (requests per interval)
active-max-number:    # default 100. If more than this number of active proxies, the extra will be deprecated by speed

# cloudflare api
cf_email: ""
cf_key: ""

#tg_channel_proxy_url: "https://tg.i-c-a.su/rss/"
tg_channel_proxy_url: "http://127.0.0.1:9504/rss/"
#tg_channel_web_proxy_url: "http://127.0.0.1:7890"

v2_ws_header_user_agent: "user-agent:Mozilla/5.0 (iPhone; CPU iPhone OS 13_5 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1"

geoip_db_url: "https://raw.githubusercontent.com/alecthw/mmdb_china_ip_list/release/"
